name: melostest

packages:
  - app
  - modules/**
  - shared
  - design_system
  - design_system_assets

scripts:
  test:
    run: flutter test
    exec:
      concurrency: 5
    packageFilters:
      flutter: true

  update_goldens:
    run: flutter test --update-goldens
    exec:
      concurrency: 5
    packageFilters:
      flutter: true

  flutter_clean:
    run: flutter clean
    exec:
      concurrency: 5
    packageFilters:
      flutter: true

  pub_get:
    run: |
      melos exec -c 1 -- \
        "flutter pub get"
  build_runner:
    run: |
      melos exec -c 1 -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"