name: melostest
description: A new Flutter project.
homepage: https://example.com
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.13.0 <4.0.0'

dependencies:
  alice: ^1.0.0-dev.12
  alice_dio: ^1.0.6
  collection: ^1.18.0
  dio: ^5.7.0
  design_system: any
  equatable: ^2.0.5
  firebase_core: any
  firebase_crashlytics: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^7.0.0
  go_router: ^14.6.0
  http: ^1.2.2
  jaguar_jwt: ^3.0.0
  json_annotation: any
  local_session_timeout: ^3.2.0
  mfa:
  notifications:
  provider: ^6.1.2
  rx_bloc: ^6.0.0
  rxdart: ^0.28.0
  shared:
  shared_preferences: ^2.3.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  showcases:
  user:
  widget_toolkit: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.13
  clean_coverage: ^0.0.3
  copy_with_extension_gen: ^5.0.4
  flutter_lints: any
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  patrol: ^3.11.2
  r_flutter: 0.9.0
  retrofit_generator: ^9.1.3
  rx_bloc_generator: ^8.0.0
  rx_bloc_test: ^5.0.0
  test: any

patrol:
  app_name: melostest
  flavor: development
  android:
    package_name: com.example.melostest
  ios:
    bundle_id: com.example.melostest
    app_name: melostest

flutter:
  uses-material-design: true

