name: melostest
description: A new Flutter project.
homepage: https://example.com
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: '>=3.13.0 <4.0.0'

resolution: workspace

dependencies:
  alice: ^1.0.0-dev.12
  alice_dio: ^1.0.6
  collection: 1.19.0
  design_system: any
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_core: any
  firebase_crashlytics: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^7.0.0
  go_router: ^14.6.2
  http: ^1.2.2
  jaguar_jwt: ^3.0.0
  json_annotation: 4.9.0
  local_session_timeout: ^3.2.0
  mfa:
  notifications:
  provider: ^6.1.2
  rx_bloc: ^6.0.0
  rxdart: ^0.28.0
  shared: any
  shared_preferences: ^2.3.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  showcases:
  user:
  widget_toolkit: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.14
#  clean_coverage: ^0.0.3
  flutter_lints: any
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  mockito: ^5.4.5
  patrol: ^3.13.1
  r_flutter: 0.9.0
  retrofit_generator: ^9.1.5
  rx_bloc_generator: ^8.0.0
  rx_bloc_test: ^5.0.0
  test: any

patrol:
  app_name: melostest
  flavor: development
  android:
    package_name: com.example.melostest
  ios:
    bundle_id: com.example.melostest
    app_name: melostest

flutter:
  uses-material-design: true

