name: shared
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  assets:
    path: ../assets
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_rx_bloc: ^7.0.0
  firebase_analytics: ^11.3.5
  copy_with_extension: ^5.0.4
  json_annotation: ^4.9.0
  firebase_crashlytics: ^4.1.5
  widget_toolkit: ^0.2.0
  alice: ^1.0.0-dev.12
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  alice_dio: ^1.0.6
  retrofit: ^4.4.1
  local_session_timeout: ^3.2.0
  widget_toolkit_biometrics: ^0.1.0
  flutter_secure_storage: ^9.2.2
  widget_toolkit_pin: ^0.2.2
  widget_toolkit_otp: ^0.1.0
  widget_toolkit_qr: ^0.2.0
  go_router: ^14.6.0
  rx_bloc: ^6.0.0
  rxdart: ^0.28.0
  equatable: ^2.0.5
  crypto: ^3.0.6
  collection: ^1.18.0
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  rx_bloc_generator: ^8.0.0
  golden_toolkit: ^0.15.0
  mockito: ^5.4.4
  rx_bloc_test: ^5.0.0
  r_flutter: ^0.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package

r_flutter:
  intl: lib/src/l10n/arb/en.arb
  intl_features:
    - name: error
    - name: feature_mfa
    - name: feature_counter
    - name: feature_deep_link
    - name: feature_enter_message
    - name: feature_login
    - name: feature_notifications
    - name: feature_otp
    - name: feature_profile
    - name: feature_qr
    - name: feature_showcase
    - name: feature_widget_toolkit
    - name: field
    - name: lib_change_language
    - name: lib_dev_menu
    - name: lib_pin_code
    - name: lib_router